@baseUrl=http://localhost:3000
@repositoryEndpoint={{baseUrl}}/repositories
@resultEndpoint={{baseUrl}}/results

###

GET {{repositoryEndpoint}}

###

POST {{repositoryEndpoint}}
Content-Type: application/json

{
    "name": "echo",
    "url": "https://github.com/labstack/echo"
}

###

DELETE {{repositoryEndpoint}}/1

###

POST {{repositoryEndpoint}}/66/scans

###

GET {{resultEndpoint}}

### 

POST {{repositoryEndpoint}}/61/scans